name: draftmode_formatter
description: Collection of lightweight formatters
version: 0.0.0+1
homepage: https://draftmode.io/dev/flutter/formatter
license: MIT

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

repository: https://github.com/draftm0de/flutter.formatter
issue_tracker: https://github.com/draftm0de/flutter.formatter/issues